#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CID=$(< "$ADDON_DATA/CONTAINER")

docker stop $CID > /dev/null || true
docker run -rm -v $ADDON_DATA:/opt/postgresql addons/postgresql rm -Rf /opt/postgresql/data

rm -Rf $ADDON_DATA/CONTAINER $ADDON_DATA/PASSWORD

