#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CONTAINER_FILE="$ADDON_DATA/CONTAINER"
PASSWORD_FILE="$ADDON_DATA/PASSWORD"

if [[ $DOKKU_TRACE ]]; then
  docker build -rm -t addons/postgresql $ADDON_ROOT
else
  docker build -rm -q -t addons/postgresql $ADDON_ROOT > /dev/null
fi

set +o pipefail
ROOT_PASSWORD=$(< /dev/urandom tr -dc 'A-Za-z0-9' | head -c 32)
set -o pipefail

echo $ROOT_PASSWORD > $PASSWORD_FILE

CID=$(docker run -d -v $ADDON_DATA:/opt/postgresql addons/postgresql)

echo $CID > $CONTAINER_FILE

