#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CID=$(< $ADDON_DATA/CONTAINER)

ID="$1"
PASSWORD="$2"

IP=$(docker inspect $CID | grep IPAddress | cut -d '"' -f 4)

cat | docker run -i -rm -e PGPASSWORD="$PASSWORD" addons/postgresql psql -q -1 -v ON_ERROR_STOP=1 -h $IP -U $ID -w $ID

