#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CONTAINER_FILE="$ADDON_DATA/CONTAINER"
PASSWORD_FILE="$ADDON_DATA/PASSWORD"

ID="$1"

CID=$(cat $CONTAINER_FILE)
IP=$(docker inspect $CID | grep IPAddress | cut -d '"' -f 4)
ROOT_PASSWORD=$(cat $PASSWORD_FILE)

docker run -i -rm -e PGPASSWORD="$ROOT_PASSWORD" addons/postgresql psql -q -1 -v ON_ERROR_STOP=1 -h $IP -U postgres -w <<EOF
DROP DATABASE "$ID";
DROP USER "$ID";
EOF


