#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CONTAINER_FILE="$ADDON_DATA/CONTAINER"

USER=$1
PASS=$2

CID=$(cat $CONTAINER_FILE)
IP=$(docker inspect $CID | grep IPAddress | cut -d '"' -f 4)

echo "mysql://$USER:$PASS@$IP:5432/$USER"

