#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CONTAINER_FILE="$ADDON_DATA/CONTAINER"
PASSWORD_FILE="$ADDON_DATA/PASSWORD"

docker build -rm -t addons/mariadb $ADDON_ROOT

set +o pipefail
ROOT_PASSWORD=$(< /dev/urandom tr -dc 'A-Za-z0-9' | head -c 32)
set -o pipefail

echo $ROOT_PASSWORD > $PASSWORD_FILE

CID=$(docker run -d -v $ADDON_DATA:/opt/mysql addons/mariadb)

echo $CID > $CONTAINER_FILE

