#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

ID="$1"
PASSWORD="$2"

APPDIR="$ADDON_DATA/$ID"

CID=$(< $APPDIR/CONTAINER)

IP=$(docker inspect $CID | grep IPAddress | cut -d '"' -f 4)

docker run -rm addons/redis redis-cli -h $IP -a $PASSWORD SAVE > /dev/null

cat $APPDIR/data/dump.rdb

