#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ $DOKKU_TRACE ]]; then
  docker build -rm -t addons/redis $ADDON_ROOT
else
  docker build -rm -q -t addons/redis $ADDON_ROOT > /dev/null
fi

