#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

ID="$1"
DATADIR="$ADDON_DATA/$ID"
CID=$(< "$DATADIR/CONTAINER")

docker stop $CID > /dev/null || true
docker run -rm -v $DATADIR:/opt/redis addons/redis rm -Rf /opt/redis/data 

rm -Rf $DATADIR


